include:
    - template: Security/Dependency-Scanning.gitlab-ci.yml
    - template: Security/Secret-Detection.gitlab-ci.yml
    - template: Jobs/SAST.gitlab-ci.yml

stages:
    - build
    - test
    - deploy

build:
    image: gradle:8.2.0-jdk17
    stage: build
    script:
        - gradle clean bootBuildImage
    artifacts:
        when: always
        paths:
            - build/libs/*.jar


test:
    image: gradle:8.2.0-jdk17
    stage: test
    script:
        - gradle test
    artifacts:
        when: always
        reports:
            junit: ./build/test-results/test/**/TEST-*.xml


deploy:
    image: mcr.microsoft.com/azure-cli
    stage: deploy
    before_script:
        - az login --service-principal -u $PRINCIPAL_AZURE_APP_ID -p $PRINCIPAL_AZURE_PASSWORD --tenant $PRINCIPAL_AZURE_TENANT
        - az extension add --name container-app --upgrade
    script:
        - tag=$CI_COMMIT_REF_NAME
        - az containerapp up
