include:
    - template: Security/Dependency-Scanning.gitlab-ci.yml
    - template: Security/Secret-Detection.gitlab-ci.yml
    - template: Jobs/SAST.gitlab-ci.yml


variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""


image: docker:latest
services:
    - docker:dind


cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
        - build
        - .gradle


stages:
    - build
    - test
    - deploy


build:
    image: gradle:8.4.0-jdk21
    stage: build
    only:
        - main
    script:
        - gradle clean bootBuildImage


test:
    image: gradle:8.4.0-jdk21
    stage: test
    script:
        - gradle test
    artifacts:
        when: always
        reports:
            junit: ./build/test-results/test/**/TEST-*.xml


deploy:
    image: mcr.microsoft.com/azure-cli
    stage: deploy
    only:
        - main
    before_script:
        - az login --service-principal -u $PRINCIPAL_AZURE_APP_ID -p $PRINCIPAL_AZURE_PASSWORD --tenant $PRINCIPAL_AZURE_TENANT
        - az extension add --name containerapp --upgrade
    script:
        - tag=$CI_COMMIT_REF_NAME
        - az containerapp up --name airene-backend --resource-group containerapps --location westeurope --environment prod --target-port 8080 --ingress external --image "$IMAGE_USERNAME.azurecr.io/airene-backend:latest"
        - az containerapp secret set --name airene-backend --resource-group containerapps --secrets
            azure-sb-namespace=$AZURE_SERVICEBUS_NAMESPACE
            azure-sb-connection=$AZURE_SERVICEBUS_CONNECTION_STRING
            azure-sql-db-un=$AZURE_SQL_DB_USERNAME
            azure-sql-db-pw=$AZURE_SQL_DB_PASSWORD
            azure-sql-db-url=$AZURE_SQL_DB_URL
            keycloak-issuer=$KEYCLOAK_ISSUER
            keycloak-jwt=$KEYCLOAK_JWT
            azure-mail-endpoint=$AZURE_MAIL_ENDPOINT
            azure-mail-sender=$AZURE_MAIL_SENDER
            frontend-domain=$FRONTEND_DOMAIN
            sentry-token=$SENTRY_AUTH_TOKEN
        - az containerapp update --name airene-backend --resource-group containerapps --cpu 1 --memory 2Gi --set-env-vars
            AZURE_SERVICEBUS_NAMESPACE=secretref:azure-sb-namespace
            AZURE_SERVICEBUS_CONNECTION_STRING=secretref:azure-sb-connection
            AZURE_SQL_DB_USERNAME=secretref:azure-sql-db-un
            AZURE_SQL_DB_PASSWORD=secretref:azure-sql-db-pw
            AZURE_SQL_DB_URL=secretref:azure-sql-db-url
            SPRING_PROFILES_ACTIVE=prod
            KEYCLOAK_ISSUER=secretref:keycloak-issuer
            KEYCLOAK_JWT=secretref:keycloak-jwt
            AZURE_MAIL_ENDPOINT=secretref:azure-mail-endpoint
            AZURE_MAIL_SENDER=secretref:azure-mail-sender
            FRONTEND_DOMAIN=secretref:frontend-domain
            SENTRY_AUTH_TOKEN=secretref:sentry-token
        - az containerapp update --name airene-backend --resource-group containerapps --yaml containerapp.yaml
