### Token Regular
POST {{tokenURL}}
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=password&username={{username}}&password={{password}}

> {%
    client.global.set("access_token", response.body.access_token);
%}



###
GET {{baseUrl}}/api/anomalies
Authorization: Bearer {{access_token}}
