spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${AZURE_ENTRA_CLIENT_ID}
        session-stateless: true
        app-id-uri: ${AZURE_ENTRA_APP_ID_URI}
