spring:
  cloud:
    azure:
      servicebus:
        namespace: ${AZURE_SERVICEBUS_NAMESPACE}
        entity-type: queue
        connection-string: ${AZURE_SERVICEBUS_CONNECTION_STRING}
  datasource:
    url: ${AZURE_SQL_DB_URL}
    username: ${AZURE_SQL_DB_USERNAME}
    password: ${AZURE_SQL_DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWT}
          issuer-uri: ${KEYCLOAK_ISSUER}

azure:
  servicebus:
    queue:
      prediction: prediction-cute
      data: clean-data-cute
