spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${AZURE_CLIENT_ID}
        session-stateless: true
        app-id-uri: ${AZURE_APP_ID_URI}
logging:
  level:
    org:
      springframework:
          security: TRACE
